/**
 * Bamini (legacy 8-bit "typewriter" Tamil font encoding) -> real Tamil
 * Unicode converter -- lets office staff keep typing with their familiar
 * Bamini keyboard/font (still common in Tamil Nadu despite predating
 * Unicode Tamil) while everything the app actually stores, searches,
 * prints, and displays elsewhere stays genuine Tamil Unicode (U+0B80-
 * U+0BFF). See mass-intention-form.ts's "Type in Bamini" toggle -- this is
 * the pure conversion function it calls on blur; it never runs on a field
 * whose toggle is off, so a plain English name or already-Unicode Tamil
 * (typed via a real Tamil keyboard) is never touched.
 *
 * BAMINI_MAP is a straight inversion of the (extensively tested) Unicode ->
 * Bamini table from Pakeetharan/unicode-bamini-converter (MIT licensed,
 * https://github.com/Pakeetharan/unicode-bamini-converter) -- reusing a
 * real, working mapping rather than reconstructing Bamini's encoding by
 * hand, which is exactly the kind of thing that's easy to get subtly wrong.
 *
 * One known, inherent limitation carried over from the original 8-bit
 * encoding itself (not introduced by this inversion): the single glyph '*'
 * represents FIVE different Tamil syllables in real Bamini (ஙு/ஙூ/ஞு/ஞூ/ழூ)
 * -- all rare in everyday names/intentions. This table resolves '*' to the
 * first of those (ஙு); the other four can't be distinguished from Bamini
 * text alone and would need a manual fix if one is ever actually meant.
 *
 * Sorted longest-token-first so the greedy scanner below (baminiToUnicode)
 * never lets a short token (e.g. single "f") shadow a longer one that
 * starts the same way (e.g. "fh", "fp").
 */
const BAMINI_MAP: [string, string][] = [
  ["n[s", "ஜௌ"],
  ["N[h", "ஜோ"],
  ["n[h", "ஜொ"],
  ["nfs", "கௌ"],
  ["Nfh", "கோ"],
  ["nfh", "கொ"],
  ["nqs", "ஙௌ"],
  ["Nqh", "ஙோ"],
  ["nqh", "ஙொ"],
  ["nrs", "சௌ"],
  ["Nrh", "சோ"],
  ["nrh", "சொ"],
  ["nQs", "ஞௌ"],
  ["NQh", "ஞோ"],
  ["nQh", "ஞொ"],
  ["nls", "டௌ"],
  ["Nlh", "டோ"],
  ["nlh", "டொ"],
  ["nzs", "ணௌ"],
  ["Nzh", "ணோ"],
  ["nzh", "ணொ"],
  ["njs", "தௌ"],
  ["Njh", "தோ"],
  ["njh", "தொ"],
  ["nes", "நௌ"],
  ["Neh", "நோ"],
  ["neh", "நொ"],
  ["nds", "னௌ"],
  ["Ndh", "னோ"],
  ["ndh", "னொ"],
  ["ngs", "பௌ"],
  ["Ngh", "போ"],
  ["ngh", "பொ"],
  ["nks", "மௌ"],
  ["Nkh", "மோ"],
  ["nkh", "மொ"],
  ["nas", "யௌ"],
  ["Nah", "யோ"],
  ["nah", "யொ"],
  ["nus", "ரௌ"],
  ["Nuh", "ரோ"],
  ["nuh", "ரொ"],
  ["nys", "லௌ"],
  ["Nyh", "லோ"],
  ["nyh", "லொ"],
  ["nss", "ளௌ"],
  ["Nsh", "ளோ"],
  ["nsh", "ளொ"],
  ["nts", "வௌ"],
  ["Nth", "வோ"],
  ["nth", "வொ"],
  ["nos", "ழௌ"],
  ["Noh", "ழோ"],
  ["noh", "ழொ"],
  ["nws", "றௌ"],
  ["Nwh", "றோ"],
  ["nwh", "றொ"],
  ["n`s", "ஹௌ"],
  ["N`h", "ஹோ"],
  ["n`h", "ஹொ"],
  ["n\\s", "ஷௌ"],
  ["N\\h", "ஷோ"],
  ["n\\h", "ஷொ"],
  ["n]s", "ஸௌ"],
  ["N]h", "ஸோ"],
  ["n]h", "ஸொ"],
  ["[h", "ஜா"],
  ["[p", "ஜி"],
  ["[P", "ஜீ"],
  ["[{", "ஜு"],
  ["[_", "ஜூ"],
  ["n[", "ஜெ"],
  ["N[", "ஜே"],
  ["i[", "ஜை"],
  ["[;", "ஜ்"],
  ["fh", "கா"],
  ["fp", "கி"],
  ["fP", "கீ"],
  ["nf", "கெ"],
  ["Nf", "கே"],
  ["if", "கை"],
  ["f;", "க்"],
  ["qh", "ஙா"],
  ["qp", "ஙி"],
  ["qP", "ஙீ"],
  ["nq", "ஙெ"],
  ["Nq", "ஙே"],
  ["iq", "ஙை"],
  ["q;", "ங்"],
  ["rh", "சா"],
  ["rp", "சி"],
  ["rP", "சீ"],
  ["R+", "சூ"],
  ["nr", "செ"],
  ["Nr", "சே"],
  ["ir", "சை"],
  ["r;", "ச்"],
  ["Qh", "ஞா"],
  ["Qp", "ஞி"],
  ["QP", "ஞீ"],
  ["nQ", "ஞெ"],
  ["NQ", "ஞே"],
  ["iQ", "ஞை"],
  ["Q;", "ஞ்"],
  ["lh", "டா"],
  ["nl", "டெ"],
  ["Nl", "டே"],
  ["il", "டை"],
  ["l;", "ட்"],
  ["zh", "ணா"],
  ["zp", "ணி"],
  ["zP", "ணீ"],
  ["Z}", "ணூ"],
  ["nz", "ணெ"],
  ["Nz", "ணே"],
  ["iz", "ணை"],
  ["z;", "ண்"],
  ["jh", "தா"],
  ["jp", "தி"],
  ["jP", "தீ"],
  ["J}", "தூ"],
  ["nj", "தெ"],
  ["Nj", "தே"],
  ["ij", "தை"],
  ["j;", "த்"],
  ["eh", "நா"],
  ["ep", "நி"],
  ["eP", "நீ"],
  ["E}", "நூ"],
  ["ne", "நெ"],
  ["Ne", "நே"],
  ["ie", "நை"],
  ["e;", "ந்"],
  ["dh", "னா"],
  ["dp", "னி"],
  ["dP", "னீ"],
  ["D}", "னூ"],
  ["nd", "னெ"],
  ["Nd", "னே"],
  ["id", "னை"],
  ["d;", "ன்"],
  ["gh", "பா"],
  ["gp", "பி"],
  ["gP", "பீ"],
  ["G+", "பூ"],
  ["ng", "பெ"],
  ["Ng", "பே"],
  ["ig", "பை"],
  ["g;", "ப்"],
  ["kh", "மா"],
  ["kp", "மி"],
  ["kP", "மீ"],
  ["nk", "மெ"],
  ["Nk", "மே"],
  ["ik", "மை"],
  ["k;", "ம்"],
  ["ah", "யா"],
  ["ap", "யி"],
  ["aP", "யீ"],
  ["A+", "யூ"],
  ["na", "யெ"],
  ["Na", "யே"],
  ["ia", "யை"],
  ["a;", "ய்"],
  ["uh", "ரா"],
  ["up", "ரி"],
  ["uP", "ரீ"],
  ["\\&", "ரூ"],
  ["nu", "ரெ"],
  ["Nu", "ரே"],
  ["iu", "ரை"],
  ["u;", "ர்"],
  ["yh", "லா"],
  ["yp", "லி"],
  ["yP", "லீ"],
  ["Y}", "லூ"],
  ["ny", "லெ"],
  ["Ny", "லே"],
  ["iy", "லை"],
  ["y;", "ல்"],
  ["sh", "ளா"],
  ["sp", "ளி"],
  ["sP", "ளீ"],
  ["Sh", "ளூ"],
  ["ns", "ளெ"],
  ["Ns", "ளே"],
  ["is", "ளை"],
  ["s;", "ள்"],
  ["th", "வா"],
  ["tp", "வி"],
  ["tP", "வீ"],
  ["T+", "வூ"],
  ["nt", "வெ"],
  ["Nt", "வே"],
  ["it", "வை"],
  ["t;", "வ்"],
  ["oh", "ழா"],
  ["op", "ழி"],
  ["oP", "ழீ"],
  ["no", "ழெ"],
  ["No", "ழே"],
  ["io", "ழை"],
  ["o;", "ழ்"],
  ["wh", "றா"],
  ["wp", "றி"],
  ["wP", "றீ"],
  ["W}", "றூ"],
  ["nw", "றெ"],
  ["Nw", "றே"],
  ["iw", "றை"],
  ["w;", "ற்"],
  ["`h", "ஹா"],
  ["`p", "ஹி"],
  ["`P", "ஹீ"],
  ["{`", "ஹு"],
  ["`_", "ஹூ"],
  ["n`", "ஹெ"],
  ["N`", "ஹே"],
  ["i`", "ஹை"],
  ["`;", "ஹ்"],
  ["\\h", "ஷா"],
  ["\\p", "ஷி"],
  ["\\P", "ஷீ"],
  ["\\_", "ஷூ"],
  ["n\\", "ஷெ"],
  ["N\\", "ஷே"],
  ["i\\", "ஷை"],
  ["\\;", "ஷ்"],
  ["]h", "ஸா"],
  ["]p", "ஸி"],
  ["]P", "ஸீ"],
  ["]{", "ஸு"],
  ["]_", "ஸூ"],
  ["n]", "ஸெ"],
  ["N]", "ஸே"],
  ["i]", "ஸை"],
  ["];", "ஸ்"],
  ["xs", "ஔ"],
  ["=", "ஸ்ரீ"],
  [">", ","],
  ["[", "ஜ"],
  ["F", "கு"],
  ["$", "கூ"],
  ["f", "க"],
  ["*", "ஙு"],
  ["q", "ங"],
  ["R", "சு"],
  ["r", "ச"],
  ["Q", "ஞ"],
  ["b", "டி"],
  ["B", "டீ"],
  ["L", "டு"],
  ["^", "டூ"],
  ["l", "ட"],
  ["Z", "ணு"],
  ["z", "ண"],
  ["J", "து"],
  ["j", "த"],
  ["E", "நு"],
  ["e", "ந"],
  ["D", "னு"],
  ["d", "ன"],
  ["G", "பு"],
  ["g", "ப"],
  ["K", "மு"],
  ["%", "மூ"],
  ["k", "ம"],
  ["A", "யு"],
  ["a", "ய"],
  ["U", "ரு"],
  ["u", "ர"],
  ["Y", "லு"],
  ["y", "ல"],
  ["S", "ளு"],
  ["s", "ள"],
  ["T", "வு"],
  ["t", "வ"],
  ["O", "ழு"],
  ["o", "ழ"],
  ["W", "று"],
  ["w", "ற"],
  ["`", "ஹ"],
  ["{", "ஷு"],
  ["\\", "ஷ"],
  ["]", "ஸ"],
  ["m", "அ"],
  ["M", "ஆ"],
  [",", "இ"],
  ["<", "ஈ"],
  ["c", "உ"],
  ["C", "ஊ"],
  ["v", "எ"],
  ["V", "ஏ"],
  ["I", "ஐ"],
  ["x", "ஒ"],
  ["X", "ஓ"],
  ["/", "ஃ"],
];

/** Longest bamini token first -- see BAMINI_MAP's doc comment. Kept as a
 * separate constant (rather than re-sorting BAMINI_MAP itself) so the
 * source table above stays exactly traceable back to the original project's
 * entries, in their original order. */
const SORTED = [...BAMINI_MAP].sort((a, b) => b[0].length - a[0].length);

/**
 * Converts Bamini-encoded text (plain ASCII, styled with the Bamini font
 * while being typed -- see BaminiToggle usage in the Mass Intention forms)
 * into real Tamil Unicode. Greedy longest-match scan: at each position, try
 * every known Bamini token from longest to shortest; the first one that
 * matches is consumed and replaced. Any character that isn't part of any
 * known token (plain English letters/digits/punctuation a user mixed in)
 * passes through unchanged.
 */
export function baminiToUnicode(text: string): string {
  let result = '';
  let i = 0;
  outer: while (i < text.length) {
    for (const [bamini, unicode] of SORTED) {
      if (text.startsWith(bamini, i)) {
        result += unicode;
        i += bamini.length;
        continue outer;
      }
    }
    result += text[i];
    i += 1;
  }
  return result;
}
