const { renderPdfBuffer } = require('../utils/pdfPrinter');

/**
 * The Daily Prayer Register: the single most important printout in the
 * system (handed to the priest before Mass). Must be large, readable,
 * grouped by Mass, and correctly repeat its header across pages.
 */
async function generateDailyRegisterPdf({ prayerDate, church, entries, generatedBy }) {
  const groups = groupByMass(entries);
  const generatedAt = new Date();

  const body = [];
  for (const group of groups) {
    body.push({
      text: `${group.massName}  –  ${formatTime(group.massTime)}`,
      style: 'massHeader',
      margin: [0, 12, 0, 4],
    });
    body.push({
      table: {
        headerRows: 1,
        widths: [28, '18%', '*', 68, 60],
        body: [
          [
            { text: '#', style: 'tableHeader' },
            { text: 'Name', style: 'tableHeader' },
            { text: 'Prayer Intention', style: 'tableHeader' },
            { text: 'Offering', style: 'tableHeader', alignment: 'right' },
            { text: 'Receipt No.', style: 'tableHeader' },
          ],
          ...group.rows.map((row, idx) => [
            { text: String(idx + 1), style: 'cell' },
            { text: row.name, style: 'cell', bold: true },
            { text: row.intentionText, style: 'cell' },
            { text: row.offeringAmount > 0 ? formatCurrency(row.offeringAmount) : '-', style: 'cell', alignment: 'right' },
            { text: row.receiptNo, style: 'cellSmall' },
          ]),
        ],
      },
      layout: {
        fillColor: (rowIndex) => (rowIndex === 0 ? '#0B3D91' : rowIndex % 2 === 0 ? '#F4F6FB' : null),
        hLineColor: () => '#D0D5DD',
        vLineColor: () => '#D0D5DD',
      },
    });
  }

  if (!groups.length) {
    body.push({ text: 'No prayer intentions were recorded for this date.', italics: true, alignment: 'center', margin: [0, 40, 0, 0] });
  }

  const docDefinition = {
    pageSize: 'A4',
    pageMargins: [36, 90, 36, 50],
    defaultStyle: { font: 'Roboto', fontSize: 12 },
    header: (currentPage) => ({
      margin: [36, 20, 36, 0],
      stack: [
        {
          columns: [
            { text: church?.name || 'Church Office', style: 'churchName', width: '*' },
            { text: `Page ${currentPage}`, alignment: 'right', fontSize: 9, color: '#888888', width: 80 },
          ],
        },
        { text: 'DAILY PRAYER REGISTER', style: 'docTitle' },
        {
          columns: [
            { text: `Date: ${formatDate(prayerDate)}`, fontSize: 10 },
            { text: `Generated: ${generatedAt.toLocaleString()}`, alignment: 'right', fontSize: 9, color: '#888888' },
          ],
        },
        { canvas: [{ type: 'line', x1: 0, y1: 4, x2: 523, y2: 4, lineWidth: 1, lineColor: '#B08D2B' }] },
      ],
    }),
    footer: (currentPage, pageCount) => ({
      margin: [36, 0, 36, 20],
      stack: [
        { canvas: [{ type: 'line', x1: 0, y1: 0, x2: 523, y2: 0, lineWidth: 0.5, lineColor: '#D0D5DD' }] },
        {
          columns: [
            { text: `Generated by: ${generatedBy || 'System'}`, fontSize: 8, color: '#888888' },
            { text: `Page ${currentPage} of ${pageCount}`, alignment: 'right', fontSize: 8, color: '#888888' },
          ],
          margin: [0, 4, 0, 0],
        },
      ],
    }),
    content: body,
    styles: {
      churchName: { fontSize: 16, bold: true, color: '#0B3D91' },
      docTitle: { fontSize: 11, bold: true, color: '#B08D2B', margin: [0, 2, 0, 4] },
      massHeader: { fontSize: 14, bold: true, color: '#0B3D91' },
      tableHeader: { bold: true, color: '#FFFFFF', fontSize: 11 },
      cell: { fontSize: 12, margin: [0, 3, 0, 3] },
      cellSmall: { fontSize: 9, color: '#555555', margin: [0, 3, 0, 3] },
    },
  };

  return renderPdfBuffer(docDefinition);
}

function groupByMass(entries) {
  const map = new Map();
  for (const e of entries) {
    if (!map.has(e.mass_id)) {
      map.set(e.mass_id, { massId: e.mass_id, massName: e.mass_name, massTime: e.mass_time, rows: [] });
    }
    map.get(e.mass_id).rows.push({
      name: e.name,
      intentionText: e.intention_is_custom ? e.custom_intention : e.intention_master_name || e.custom_intention || '-',
      offeringAmount: Number(e.offering_amount),
      receiptNo: e.receipt_no,
    });
  }
  return Array.from(map.values()).sort((a, b) => (a.massTime > b.massTime ? 1 : -1));
}

function formatDate(d) {
  return new Date(d).toLocaleDateString('en-GB', { weekday: 'long', day: '2-digit', month: 'long', year: 'numeric' });
}
function formatTime(t) {
  if (!t) return '';
  const [h, m] = t.split(':');
  const hour = Number(h);
  const suffix = hour >= 12 ? 'PM' : 'AM';
  const hour12 = hour % 12 === 0 ? 12 : hour % 12;
  return `${hour12}:${m} ${suffix}`;
}
function formatCurrency(amount) {
  return `₹${Number(amount).toFixed(2)}`;
}

module.exports = { generateDailyRegisterPdf };
