import { Component, inject } from '@angular/core';
import { MAT_DIALOG_DATA, MatDialogModule } from '@angular/material/dialog';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatTableModule } from '@angular/material/table';
import { TranslatePipe } from '@ngx-translate/core';

export interface BulkTempPasswordRow {
  username: string;
  tempPassword: string;
}

/**
 * Shows every temp password generated by a bulk user import in one place --
 * TempPasswordDialogComponent only ever handles a single user (new-user save,
 * reset-password), and importing N users at once would otherwise mean N
 * separate dialogs with no way to review them together before handing them
 * out. Same "share this securely" note as the single-user dialog.
 */
@Component({
  selector: 'coms-bulk-temp-passwords-dialog',
  standalone: true,
  imports: [MatDialogModule, MatButtonModule, MatIconModule, MatTableModule, TranslatePipe],
  template: `
    <div class="bulk-temp-passwords">
      <mat-icon class="bulk-temp-passwords__icon">vpn_key</mat-icon>
      <h2 mat-dialog-title>{{ 'settings.newUsersCreated' | translate: { count: data.rows.length } }}</h2>
      <mat-dialog-content>
        <p>{{ 'settings.tempPasswordShareNote' | translate }}</p>
        <table mat-table [dataSource]="data.rows" class="bulk-temp-passwords__table">
          <ng-container matColumnDef="username">
            <th mat-header-cell *matHeaderCellDef>{{ 'auth.username' | translate }}</th>
            <td mat-cell *matCellDef="let row">{{ row.username }}</td>
          </ng-container>
          <ng-container matColumnDef="tempPassword">
            <th mat-header-cell *matHeaderCellDef>{{ 'settings.newPassword' | translate }}</th>
            <td mat-cell *matCellDef="let row"><code>{{ row.tempPassword }}</code></td>
          </ng-container>
          <tr mat-header-row *matHeaderRowDef="['username', 'tempPassword']"></tr>
          <tr mat-row *matRowDef="let row; columns: ['username', 'tempPassword']"></tr>
        </table>
      </mat-dialog-content>
      <mat-dialog-actions align="end">
        <button mat-flat-button color="primary" mat-dialog-close>{{ 'settings.done' | translate }}</button>
      </mat-dialog-actions>
    </div>
  `,
  styles: [
    `
      .bulk-temp-passwords {
        text-align: center;
        padding: 8px 4px;
        max-width: 480px;
      }
      .bulk-temp-passwords__icon {
        color: var(--coms-color-gold);
        font-size: 32px;
        width: 32px;
        height: 32px;
        margin-bottom: 4px;
      }
      p {
        font-size: 13px;
        color: var(--coms-text-muted);
        margin: 0 0 12px;
        text-align: left;
      }
      .bulk-temp-passwords__table {
        width: 100%;
        text-align: left;
      }
      code {
        font-family: monospace;
        font-size: 13px;
        font-weight: 700;
        color: var(--coms-color-primary);
      }
    `,
  ],
})
export class BulkTempPasswordsDialogComponent {
  data = inject<{ rows: BulkTempPasswordRow[] }>(MAT_DIALOG_DATA);
}
